remote_theme: pmarsceill/just-the-docs

title: SIMKES Khanza
description: A Jekyll theme for documentation
baseurl: "/"
url: "https://simkes.basoro.id"

permalink: pretty
exclude: ["package.json"]

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Basoro.ID":
    - "//basoro.id/"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10

plugins:
  - jekyll-seo-tag
